## exercicio 1

In [53]:
import numpy as np
conec = np.array([[1,2],[2,3],[3,4],[4,5],[5,2],[5,3],[5,1]])
C= np.array ([2,2,1,2,1,2,2])

In [54]:
#

def Assembly(conec,C):
    nv = max(conec[:,0])#numero de nos 
    nc = len(conec[:,0])# numero de linhas

    A = np.zeros((nv,nv))
    for i in range(nc):
        n1=conec [i,0]-1
        n2=conec [i,1]-1

        A[n1,n2] += -C[i]
        A[n2,n1] += -C[i]
        A[n1,n1] += C[i]
        A[n2,n2] += C[i]

    return A


In [55]:
print('A = \n',Assembly(conec,C))

A = 
 [[ 4. -2.  0.  0. -2.]
 [-2.  5. -2.  0. -1.]
 [ 0. -2.  5. -1. -2.]
 [ 0.  0. -1.  3. -2.]
 [-2. -1. -2. -2.  7.]]


## exercicios 2

In [56]:
def SolveNetwork(conec, C, natm, nB, QB):
    Atilde = Assembly (conec, C)
    natm -= 1
    nB -= 1
    Atilde [natm,:] = 0
    Atilde [natm,natm] = 1

    b = np.zeros((len(Atilde),1))
    b[nB] = QB
    pressure = np.linalg.solve(Atilde,b)

    return pressure
    

In [57]:
P = SolveNetwork(conec, C, 3, 1, 3)
print(np.round(P, 3))

[[1.398]
 [0.682]
 [0.   ]
 [0.409]
 [0.614]]


## exercicio 03


In [58]:
def KD(conec, C):
    nv = max(conec[:, 0])               # maximo de nos
    nc = len(conec[:, 0])               # numero de linhas
    K = np.zeros(shape=(nc,nc))
    D = np.zeros(shape=(nc,nv))
    
    for i in range(nc):     #diag principal
        K[i,i] = C[i]

    for k in range(nc):                  
        n1 = conec[k,0]-1
        n2 = conec[k,1]-1


        D[k,n1] = 1
        D[k,n2] = -1 

    return K, D

In [59]:
def Q(conec, C, P):
    nv = max(conec[:, 0])       # numero de nos
    nc = len(conec[:, 0])       # numero de canos
    
           
    K = np.zeros(shape=(nc,nc))
    D = np.zeros(shape=(nc,nv))

    K, D = KD(conec, C)

    return ((K @ D) @ P)

In [60]:
K, D = KD(conec, C)
print(">> K: \n", K, '\n')
print(">> D: \n", D)

>> K: 
 [[2. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 2.]] 

>> D: 
 [[ 1. -1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.]
 [ 0. -1.  0.  0.  1.]
 [ 0.  0. -1.  0.  1.]
 [-1.  0.  0.  0.  1.]]


### Damn it 

## Exercicio 04

In [ ]:
def calcula_potencia(conec,P):
    nv = max(conec[:, 0])              # numero de nos
    nc = len(conec[:, 0])       # numero de canos
    
    K = np.zeros(shape=(nc,nc))
    D = np.zeros(shape=(nc,nv))

    K, D = KD(conec, C)
    return (np.transpose(P)@(np.transpose(D) @ K @ D ) @ P )


## Exercicio 

In [ ]:
def Assemblye(conec, C, nv, nc):
    A = np.zeros(shape=(nv,nv)
    for k in range(nc):
        n1= conec [k,0]
        n2=conec  [k,1]

        A[n1,n2] += -C[k]
        A[n2,n2] += -C[k]
        A[n2,n2] += C[k]
        A[n1,n1] += C[k]

    return A

def ResolveRede(conec, C , natm, nB, QB, nv, nc):
    Atilde = Assemblye(conec, C, nv, nc)
    natm -= 1
    nB -= 1
    


